# Generated by Django 4.2.30 on 2026-05-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='Unique case identifier (e.g. "tutorial_mirna_auto_robado")', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_scene_id', models.CharField(help_text='Scene ID where this case begins', max_length=100)),
            ],
            options={
                'verbose_name': 'Case',
                'ordering': ['case_id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_beat', models.PositiveIntegerField(help_text='Beat index (0-based) after which this choice appears')),
                ('prompt', models.TextField(help_text='Question shown to the player')),
            ],
            options={
                'verbose_name': 'Choice',
                'ordering': ['at_beat'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(help_text='Button label shown to player', max_length=500)),
                ('goto', models.CharField(blank=True, help_text='Scene ID to jump to after option beats play (optional)', max_length=100)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dispatcher_authoring.choice')),
            ],
            options={
                'verbose_name': 'Choice Option',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GameProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dispatcher', max_length=200)),
                ('start_scene_id', models.CharField(default='intro', help_text='ID of the first scene to play (must exist in Scenes)', max_length=100)),
                ('cinema_image', models.CharField(blank=True, max_length=500)),
                ('cinema_studio', models.CharField(blank=True, max_length=200)),
                ('cinema_title', models.CharField(blank=True, max_length=200)),
                ('cinema_place', models.CharField(blank=True, max_length=200)),
                ('cinema_text', models.TextField(blank=True, help_text='HTML allowed (e.g. <br>)')),
                ('whatsapp_default_contact', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game Project',
            },
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vignette_id', models.CharField(help_text='Key used in JSON (e.g. "office")', max_length=100)),
                ('image', models.CharField(help_text='Relative path to image asset', max_length=500)),
                ('label', models.CharField(blank=True, help_text='Location/label shown on screen', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Subtitle shown below label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vignettes', to='dispatcher_authoring.gameproject')),
            ],
            options={
                'verbose_name': 'Vignette',
                'ordering': ['vignette_id'],
            },
        ),
        migrations.CreateModel(
            name='ToolSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.CharField(help_text='Tool key (e.g. "address", "vehicle")', max_length=100)),
                ('title', models.CharField(help_text='Panel title shown to player', max_length=200)),
                ('hint', models.TextField(blank=True, help_text='Hint text shown above the search input')),
                ('placeholder', models.CharField(blank=True, help_text='Input placeholder text', max_length=200)),
                ('match_patterns', models.JSONField(blank=True, default=list, help_text='Strings that trigger a successful match (array of strings)')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Result payload — use {"result": {...}} for map searches or {"models": [...]} for catalog searches. This is merged directly into the exported JSON.')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_searches', to='dispatcher_authoring.case')),
            ],
            options={
                'verbose_name': 'Tool Search',
                'verbose_name_plural': 'Tool Searches',
                'ordering': ['search_id'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.CharField(help_text='Unique scene identifier (e.g. "intro")', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('objective', models.TextField(blank=True, help_text='Internal note — scene purpose')),
                ('channel', models.CharField(blank=True, choices=[('narration', 'Narration'), ('911', '911 Call'), ('whatsapp', 'WhatsApp'), ('', 'Other / Not set')], help_text='"911", "narration", "whatsapp", etc.', max_length=50)),
                ('next_scene_id', models.CharField(blank=True, help_text='ID of the scene to play after this one (leave blank if choices control flow)', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='dispatcher_authoring.gameproject')),
            ],
            options={
                'verbose_name': 'Scene',
                'ordering': ['scene_id'],
            },
        ),
        migrations.CreateModel(
            name='OptionBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Beat order within its parent (0-based)')),
                ('kind', models.CharField(blank=True, choices=[('', 'Dialogue (speaker)'), ('narration', 'Narration'), ('vignette', 'Vignette'), ('input', 'Input'), ('tool-search', 'Tool Search')], default='', help_text='Leave blank for a dialogue beat with a speaker', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('speaker', models.CharField(blank=True, help_text='Speaker name — only for Dialogue beats', max_length=200)),
                ('vignette_ref', models.CharField(blank=True, help_text='Vignette ID — only for Vignette beats (e.g. "office")', max_length=100)),
                ('input_field', models.CharField(blank=True, help_text='CaseField ID — only for Input beats (e.g. "plate")', max_length=100)),
                ('input_set_value', models.CharField(blank=True, help_text='setValue — pre-filled value for the input', max_length=500)),
                ('input_answer', models.CharField(blank=True, help_text='answer — accepted answer string', max_length=500)),
                ('input_hint', models.TextField(blank=True, help_text='hint — shown to player')),
                ('tool_ref', models.CharField(blank=True, help_text='ToolSearch ID — only for Tool Search beats (e.g. "address")', max_length=100)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='dispatcher_authoring.choiceoption')),
            ],
            options={
                'verbose_name': 'Option Beat',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManualCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('cat_id', models.CharField(help_text='Slug identifier (e.g. "vehiculo_robado")', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('keys', models.JSONField(default=list, help_text='Keywords that trigger this category')),
                ('when', models.TextField(help_text='When to use this category')),
                ('steps', models.JSONField(default=list, help_text='Steps list (array of strings)')),
                ('avoid', models.JSONField(default=list, help_text='Things to avoid (array of strings)')),
                ('dispatch', models.CharField(help_text='Dispatch recommendation text', max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_categories', to='dispatcher_authoring.gameproject')),
            ],
            options={
                'verbose_name': 'Manual Category',
                'verbose_name_plural': 'Manual Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DispatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(help_text='Title shown on dispatch screen', max_length=200)),
                ('available_units', models.JSONField(default=list, help_text='Array of unit objects: [{"id": "Carabineros", "icon": "🚔", "desc": "..."}]')),
                ('required_units', models.JSONField(default=list, help_text='Array of required unit IDs: ["Carabineros", "Seguridad Ciudadana"]')),
                ('next_scene_id', models.CharField(blank=True, help_text='Scene to play after dispatch is resolved', max_length=100)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_rule', to='dispatcher_authoring.case')),
            ],
            options={
                'verbose_name': 'Dispatch Rule',
            },
        ),
        migrations.CreateModel(
            name='DispatchOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_id', models.CharField(help_text='Outcome key (e.g. "complete")', max_length=100)),
                ('match_type', models.CharField(blank=True, help_text='"all_required" to match when all required units are dispatched. Leave blank and fill match_units for partial matches.', max_length=50)),
                ('match_units', models.JSONField(blank=True, default=list, help_text='List of unit IDs for partial match (used when match_type is blank)')),
                ('notification', models.CharField(help_text='Notification label shown to player', max_length=200)),
                ('beats_json', models.JSONField(default=list, help_text='Beats played after this outcome. Same format as scene beats JSON.')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='dispatcher_authoring.dispatchrule')),
            ],
            options={
                'verbose_name': 'Dispatch Outcome',
                'ordering': ['outcome_id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(help_text='Key used in JSON (e.g. "dani")', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional contact fields (avatar, phone, etc.) as JSON')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dispatcher_authoring.gameproject')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['contact_id'],
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='dispatcher_authoring.scene'),
        ),
        migrations.CreateModel(
            name='CaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(help_text='Field key (e.g. "plate", "local")', max_length=100)),
                ('fact_path', models.CharField(help_text='Dot-notation path in facts object (e.g. "facts.plate")', max_length=200)),
                ('log_template', models.CharField(help_text='Log message template (e.g. "✔ Patente: {value}")', max_length=500)),
                ('notification_label', models.CharField(help_text='Notification label shown to player (e.g. "PATENTE REGISTRADA")', max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_fields', to='dispatcher_authoring.case')),
            ],
            options={
                'verbose_name': 'Case Field',
                'ordering': ['field_id'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='dispatcher_authoring.gameproject'),
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Beat order within its parent (0-based)')),
                ('kind', models.CharField(blank=True, choices=[('', 'Dialogue (speaker)'), ('narration', 'Narration'), ('vignette', 'Vignette'), ('input', 'Input'), ('tool-search', 'Tool Search')], default='', help_text='Leave blank for a dialogue beat with a speaker', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('speaker', models.CharField(blank=True, help_text='Speaker name — only for Dialogue beats', max_length=200)),
                ('vignette_ref', models.CharField(blank=True, help_text='Vignette ID — only for Vignette beats (e.g. "office")', max_length=100)),
                ('input_field', models.CharField(blank=True, help_text='CaseField ID — only for Input beats (e.g. "plate")', max_length=100)),
                ('input_set_value', models.CharField(blank=True, help_text='setValue — pre-filled value for the input', max_length=500)),
                ('input_answer', models.CharField(blank=True, help_text='answer — accepted answer string', max_length=500)),
                ('input_hint', models.TextField(blank=True, help_text='hint — shown to player')),
                ('tool_ref', models.CharField(blank=True, help_text='ToolSearch ID — only for Tool Search beats (e.g. "address")', max_length=100)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='dispatcher_authoring.scene')),
            ],
            options={
                'verbose_name': 'Beat',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('music', 'Music'), ('sfx', 'SFX')], default='music', max_length=10)),
                ('key', models.CharField(help_text='Key used in JSON (e.g. "rain", "notif")', max_length=100)),
                ('path', models.CharField(help_text='Relative path to audio file', max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_assets', to='dispatcher_authoring.gameproject')),
            ],
            options={
                'verbose_name': 'Audio Asset',
                'ordering': ['asset_type', 'key'],
            },
        ),
    ]
