# Generated by Django 4.2.30 on 2026-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_authoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='ambient_key',
            field=models.CharField(blank=True, help_text='Ambient key (e.g. rain)', max_length=100),
        ),
        migrations.AddField(
            model_name='beat',
            name='ambient_stop',
            field=models.BooleanField(default=False, help_text='Set true to stop ambient audio'),
        ),
        migrations.AddField(
            model_name='beat',
            name='media_caption',
            field=models.TextField(blank=True, help_text='Caption for image/file media'),
        ),
        migrations.AddField(
            model_name='beat',
            name='media_duration',
            field=models.CharField(blank=True, help_text='Voice note duration (e.g. 0:12)', max_length=20),
        ),
        migrations.AddField(
            model_name='beat',
            name='media_name',
            field=models.CharField(blank=True, help_text='File display name', max_length=200),
        ),
        migrations.AddField(
            model_name='beat',
            name='media_type',
            field=models.CharField(blank=True, help_text='image | voice | file — only for wa beats', max_length=20),
        ),
        migrations.AddField(
            model_name='beat',
            name='media_url',
            field=models.CharField(blank=True, help_text='Media URL/path — image/file source', max_length=500),
        ),
        migrations.AddField(
            model_name='beat',
            name='sfx_key',
            field=models.CharField(blank=True, help_text='SFX key (e.g. notif)', max_length=100),
        ),
        migrations.AddField(
            model_name='beat',
            name='wa_contact',
            field=models.CharField(blank=True, help_text='WA contact ID (e.g. "dani") — only for wa beats', max_length=100),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='ambient_key',
            field=models.CharField(blank=True, help_text='Ambient key (e.g. rain)', max_length=100),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='ambient_stop',
            field=models.BooleanField(default=False, help_text='Set true to stop ambient audio'),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='media_caption',
            field=models.TextField(blank=True, help_text='Caption for image/file media'),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='media_duration',
            field=models.CharField(blank=True, help_text='Voice note duration (e.g. 0:12)', max_length=20),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='media_name',
            field=models.CharField(blank=True, help_text='File display name', max_length=200),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='media_type',
            field=models.CharField(blank=True, help_text='image | voice | file — only for wa beats', max_length=20),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='media_url',
            field=models.CharField(blank=True, help_text='Media URL/path — image/file source', max_length=500),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='sfx_key',
            field=models.CharField(blank=True, help_text='SFX key (e.g. notif)', max_length=100),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='wa_contact',
            field=models.CharField(blank=True, help_text='WA contact ID (e.g. "dani") — only for wa beats', max_length=100),
        ),
        migrations.AlterField(
            model_name='beat',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Dialogue (speaker)'), ('narration', 'Narration'), ('vignette', 'Vignette'), ('input', 'Input'), ('tool-search', 'Tool Search'), ('wa', 'WhatsApp Media (wa)'), ('sfx', 'SFX Trigger'), ('ambient', 'Ambient Trigger')], default='', help_text='Leave blank for a dialogue beat with a speaker', max_length=20),
        ),
        migrations.AlterField(
            model_name='optionbeat',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Dialogue (speaker)'), ('narration', 'Narration'), ('vignette', 'Vignette'), ('input', 'Input'), ('tool-search', 'Tool Search'), ('wa', 'WhatsApp Media (wa)'), ('sfx', 'SFX Trigger'), ('ambient', 'Ambient Trigger')], default='', help_text='Leave blank for a dialogue beat with a speaker', max_length=20),
        ),
    ]
