# Generated by Django 4.2.30 on 2026-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_authoring', '0002_beat_ambient_key_beat_ambient_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='vignette_action',
            field=models.CharField(blank=True, choices=[('', 'Legacy (auto-close tras timer)'), ('open', 'open — abrir plano (imagen persiste)'), ('text', 'text — actualizar texto (imagen persiste)'), ('change', 'change — cambiar plano/imagen'), ('close', 'close — cerrar viñeta, volver al juego')], default='', help_text='Acción cinematográfica: open → abrir plano; text → actualizar texto; change → cambiar plano; close → cerrar viñeta. Dejar vacío para comportamiento legacy (auto-close).', max_length=20),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='vignette_action',
            field=models.CharField(blank=True, choices=[('', 'Legacy (auto-close tras timer)'), ('open', 'open — abrir plano (imagen persiste)'), ('text', 'text — actualizar texto (imagen persiste)'), ('change', 'change — cambiar plano/imagen'), ('close', 'close — cerrar viñeta, volver al juego')], default='', help_text='Acción cinematográfica: open → abrir plano; text → actualizar texto; change → cambiar plano; close → cerrar viñeta. Dejar vacío para comportamiento legacy (auto-close).', max_length=20),
        ),
        migrations.AlterField(
            model_name='beat',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Dialogue (speaker)'), ('narration', 'Narration'), ('vignette', 'Vignette / Cinemática'), ('input', 'Input'), ('tool-search', 'Tool Search'), ('wa', 'WhatsApp Media (wa)'), ('sfx', 'SFX Trigger'), ('ambient', 'Ambient Trigger'), ('dispatch', 'Dispatch')], default='', help_text='Leave blank for a dialogue beat with a speaker', max_length=20),
        ),
        migrations.AlterField(
            model_name='beat',
            name='vignette_ref',
            field=models.CharField(blank=True, help_text='Vignette ID (asset key) — for vignette beats (e.g. "office"). Required for action=open/change; leave blank for action=text/close.', max_length=100),
        ),
        migrations.AlterField(
            model_name='optionbeat',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Dialogue (speaker)'), ('narration', 'Narration'), ('vignette', 'Vignette / Cinemática'), ('input', 'Input'), ('tool-search', 'Tool Search'), ('wa', 'WhatsApp Media (wa)'), ('sfx', 'SFX Trigger'), ('ambient', 'Ambient Trigger'), ('dispatch', 'Dispatch')], default='', help_text='Leave blank for a dialogue beat with a speaker', max_length=20),
        ),
        migrations.AlterField(
            model_name='optionbeat',
            name='vignette_ref',
            field=models.CharField(blank=True, help_text='Vignette ID (asset key) — for vignette beats (e.g. "office"). Required for action=open/change; leave blank for action=text/close.', max_length=100),
        ),
    ]
