# Generated by Django 4.2.30 on 2026-05-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_authoring', '0004_add_fk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='input_error_msg',
            field=models.CharField(blank=True, help_text='Custom error message when answer does not match (optional). If blank, a default message is shown.', max_length=500),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='input_error_msg',
            field=models.CharField(blank=True, help_text='Custom error message when answer does not match (optional). If blank, a default message is shown.', max_length=500),
        ),
        migrations.AlterField(
            model_name='beat',
            name='input_case_field',
            field=models.ForeignKey(blank=True, help_text='Select from dropdown — preferred over Input Field text field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.casefield', verbose_name='Input Field'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='tool_ref',
            field=models.CharField(blank=True, help_text='ToolSearch ID (legacy text). Prefer tool_search FK below.', max_length=100),
        ),
        migrations.AlterField(
            model_name='beat',
            name='tool_search',
            field=models.ForeignKey(blank=True, help_text='Select from dropdown — preferred over Tool Ref text field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.toolsearch', verbose_name='Tool Search'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='vignette',
            field=models.ForeignKey(blank=True, help_text='Select from dropdown — preferred over Vignette Ref text field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.vignette', verbose_name='Vignette'),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_scene',
            field=models.ForeignKey(blank=True, help_text='Scene where this case begins. Select from dropdown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.scene', verbose_name='Start Scene'),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_scene_str',
            field=models.CharField(blank=True, editable=False, help_text='Legacy text ID. Managed automatically via start_scene FK.', max_length=100),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='goto',
            field=models.CharField(blank=True, editable=False, help_text='Legacy text ID. Managed automatically via goto_scene FK.', max_length=100),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='goto_scene',
            field=models.ForeignKey(blank=True, help_text='Scene to jump to after option beats play.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.scene', verbose_name='Go To Scene'),
        ),
        migrations.AlterField(
            model_name='dispatchrule',
            name='next_scene',
            field=models.ForeignKey(blank=True, help_text='Scene to play after dispatch is resolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.scene', verbose_name='Next Scene'),
        ),
        migrations.AlterField(
            model_name='dispatchrule',
            name='next_scene_str',
            field=models.CharField(blank=True, editable=False, help_text='Legacy text ID. Managed automatically via next_scene FK.', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameproject',
            name='start_scene',
            field=models.ForeignKey(blank=True, help_text='First scene to play. Select from dropdown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.scene', verbose_name='Start Scene'),
        ),
        migrations.AlterField(
            model_name='gameproject',
            name='start_scene_str',
            field=models.CharField(blank=True, default='intro', editable=False, help_text='Legacy text ID. Managed automatically via start_scene FK.', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameproject',
            name='whatsapp_default_contact',
            field=models.CharField(blank=True, editable=False, help_text='Legacy text ID. Managed automatically via wa_default_contact FK.', max_length=100),
        ),
        migrations.AlterField(
            model_name='optionbeat',
            name='input_case_field',
            field=models.ForeignKey(blank=True, help_text='Select from dropdown — preferred over Input Field text field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.casefield', verbose_name='Input Field'),
        ),
        migrations.AlterField(
            model_name='optionbeat',
            name='tool_ref',
            field=models.CharField(blank=True, help_text='ToolSearch ID (legacy text). Prefer tool_search FK below.', max_length=100),
        ),
        migrations.AlterField(
            model_name='optionbeat',
            name='tool_search',
            field=models.ForeignKey(blank=True, help_text='Select from dropdown — preferred over Tool Ref text field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.toolsearch', verbose_name='Tool Search'),
        ),
        migrations.AlterField(
            model_name='optionbeat',
            name='vignette',
            field=models.ForeignKey(blank=True, help_text='Select from dropdown — preferred over Vignette Ref text field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dispatcher_authoring.vignette', verbose_name='Vignette'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Associate this scene with a case to filter inputs/tools/dispatch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='dispatcher_authoring.case', verbose_name='Case (optional)'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='next_scene',
            field=models.ForeignKey(blank=True, help_text='Scene to play after this one. Leave blank if choices control flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_scenes', to='dispatcher_authoring.scene', verbose_name='Next Scene'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='next_scene_str',
            field=models.CharField(blank=True, editable=False, help_text='Legacy text ID. Managed automatically via next_scene FK.', max_length=100),
        ),
    ]
