# Generated by Django 4.2.30 on 2026-05-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_authoring', '0005_add_input_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='sfx_action',
            field=models.CharField(blank=True, choices=[('play', 'play — iniciar / superponer'), ('replace', 'replace — detener SFX activos y reproducir este'), ('stop', 'stop — detener SFX activos')], default='play', help_text='play → superpone; replace → detiene SFX activos y reproduce este; stop → corta los SFX activos.', max_length=20),
        ),
        migrations.AddField(
            model_name='optionbeat',
            name='sfx_action',
            field=models.CharField(blank=True, choices=[('play', 'play — iniciar / superponer'), ('replace', 'replace — detener SFX activos y reproducir este'), ('stop', 'stop — detener SFX activos')], default='play', help_text='play → superpone; replace → detiene SFX activos y reproduce este; stop → corta los SFX activos.', max_length=20),
        ),
    ]